[build]
  publish = "vxn"
  functions = "netlify/functions"

# Define environment variable name (set value in Netlify UI)
[build.environment]
  RECAPTCHA_SECRET = "" # Set this in Netlify dashboard, do not commit secrets


